server:
  port: ${APP_PORT:8000}

spring:
  application:
    name: Gestion-Immobilier-App
  config:
    import: optional:secrets.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/PlatformeImmobiliere
    username: postgres
    password: hayat
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:4MB}
      max-request-size: ${MAX_REQUEST_SIZE:4MB}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging.level.org.hibernate.SQL: DEBUG

app:
  name: "Gestion Immobilier Backend"
  #  version: 1.0
  description: Application de Gestion d'immobilier
  security-scheme: Bearer Authentication
  unsecured-tag: Login

cors:
  allowed:
    origins: ${CORS_ORIGIN:http://localhost:4200}
ssl-enabled: ${UPLOAD_SSL:false}

minio:
  url: ${MINIO_URL:http://127.0.0.1:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:admin123}
  bucket-temp: ${MINIO_BUCKET_TEMP:temp}
  bucket-contrat: ${MINIO_BUCKET_CONTRAT:cnd-contrat}
  bucket-quittance: ${MINIO_BUCKET_QUITTANCE:cnd-quittance}